#/bin/sh
 
## There are several queues available.  Please check with !ITsupport to verify which queue you should use
#PBS -q celltypes
# declare that your job will use no more than 4gb of memory _at_peak_
#PBS -l mem=96g
# Allow up to 36hr of walltime.  Default is 12 hours
#PBS -l walltime=1:00:00
# request just one core on the host
#PBS -l ncpus=1
# Give your job a descriptive name. This is visible in qstat and other job reports.  Also serves as the default basename for log files
#PBS -N DMN_cortical_projection
# should torque automatically re-run the job on error?
#PBS -r n
# merge STDOUT into STDERR
#PBS -j oe
# location for stderr/stdout log files _after_ job completion
#PBS -o /allen/programs/celltypes/workgroups/mousecelltypes/T503_Connectivity_in_Alzheimer_Mice/Jennifer/cluster_code/cluster_out/myjob.out

# send email on job error
#PBS -m a
## Mail to this address
#PBS -M jenniferwh@alleninstitute.org
 
cd $PBS_O_WORKDIR   # cd to working directory where qsub was called.  Optional.
 
/allen/programs/celltypes/workgroups/mousecelltypes/T503_Connectivity_in_Alzheimer_Mice/Jennifer/cluster_code/cortical_projections/top_view_injection_polygons.py /allen/programs/celltypes/workgroups/mousecelltypes/T503_Connectivity_in_Alzheimer_Mice/Jennifer/cluster_code/cortical_projections/output


